exchange:
  name: binance
  trading_type: future  # Changed to futures trading
  test_mode: false

trading:
  base_currency: USDT
  quote_currencies:
    - BTC
    - ETH
    - XRP
    - ADA
    - LINK
    - HBAR
    - AVAX
    - DOT
    - NEAR
    - ICP
    - ONDO
    - RENDER
    - S
    - FET
    - SEI
    - STX
    - IOTA
    - KDA
    - FLUX
  timeframe: 1m
  leverage: 10
  loop_interval: 15  # Increased to 15 seconds
  order_types:
    - market
    - limit
    - stop_loss
    - take_profit

strategies:
  trend_following:
    enabled: true
    parameters:
      sma_short: 5    # 5-minute SMA
      sma_long: 15    # 15-minute SMA
      trend_threshold: 0.001  # 0.1% threshold for trend strength
      allow_default_trades: false  # Disable default trades
      force_trades: false  # Disable forced trades
      debug_mode: false  # Disable debug mode
      stop_loss_pct: 0.005   # 0.5% stop loss
      take_profit_pct: 0.01  # 1% take profit
  
  mean_reversion:
    enabled: false    # Disabled until module is created
    parameters:
      rsi_period: 5
      overbought: 65
      oversold: 35
      mean_period: 10
  
  volatility_breakout:
    enabled: false
    parameters:
      bollinger_period: 20
      bollinger_std: 2
      volume_threshold: 1.5

risk_management:
  position_sizing:
    max_position_size: 50  # Maximum 50 contracts
    risk_per_trade: 0.02   # 2% risk per trade ($0.98)
  
  stop_loss:
    enabled: true
    percentage: 0.005  # 0.5% stop loss
    trailing: true    # Enable trailing stop
  
  take_profit:
    enabled: true
    percentage: 0.01  # 1% take profit
    trailing: false
  
  portfolio:
    max_drawdown: 0.05      # 5% maximum drawdown
    max_open_positions: 3    # Allow up to 3 positions at a time
    correlation_threshold: 0.7

logging:
  level: DEBUG
  save_trades: true
  telegram_notifications: false 