exchange:
  name: binance
  trading_type: future
  test_mode: false

trading:
  base_currency: USDT
  quote_currencies:
    - BTC
    - ETH
    - XRP
    - ADA
    - LINK
    - HBAR
    - AVAX
    - DOT
    - NEAR
    - ICP
    - ONDO
    - RENDER
    - S
    - FET
    - SEI
    - STX
    - IOTA
    - KDA
    - FLUX
  timeframe: 1m
  leverage: 10
  loop_interval: 10  # Check more frequently (10 seconds)
  order_types:
    - market
    - limit
    - stop_loss
    - take_profit

strategies:
  trend_following:
    enabled: true
    parameters:
      # Strategy parameters calibrated for optimal performance
      sma_short: 5      # 5-minute SMA
      sma_long: 15      # 15-minute SMA
      trend_threshold: 0.0007  # Lower threshold to capture more opportunities
      allow_default_trades: true  # Allow trades based on standard criteria
      force_trades: false  # Don't force trades, rely on expert strategy
      debug_mode: false    # No debug mode
      stop_loss_pct: 0.006  # Slightly wider stop loss for less whipsaws
      take_profit_pct: 0.015 # Higher take profit for better reward/risk ratio
  
  # Disabled strategies (could be implemented in the future)
  mean_reversion:
    enabled: false
    parameters:
      rsi_period: 5
      overbought: 65
      oversold: 35
      mean_period: 10
  
  volatility_breakout:
    enabled: false
    parameters:
      bollinger_period: 20
      bollinger_std: 2
      volume_threshold: 1.5

risk_management:
  position_sizing:
    max_position_size: 50  # Maximum 50 contracts
    risk_per_trade: 0.02   # 2% risk per trade
  
  stop_loss:
    enabled: true
    percentage: 0.006  # 0.6% stop loss
    trailing: true     # Enable trailing stops to lock in profits
  
  take_profit:
    enabled: true
    percentage: 0.015  # 1.5% take profit
    trailing: false    # Fixed take profit levels
  
  portfolio:
    max_drawdown: 0.05     # 5% maximum drawdown
    max_open_positions: 3  # Allow up to 3 positions simultaneously
    correlation_threshold: 0.7  # Avoid highly correlated positions

logging:
  level: INFO
  save_trades: true
  telegram_notifications: false 