exchange:
  name: binance
  trading_type: future
  test_mode: false

trading:
  base_currency: USDT
  quote_currencies:
    - S
  timeframe: 1m
  leverage: 10
  loop_interval: 15
  order_types:
    - market
    - limit
    - stop_loss
    - take_profit

strategies:
  trend_following:
    enabled: true
    parameters:
      sma_short: 5
      sma_long: 15
      trend_threshold: 0.001
      allow_default_trades: true
      force_trades: true  # Always generate trades regardless of conditions
      debug_mode: false
      stop_loss_pct: 0.005
      take_profit_pct: 0.01
  
  mean_reversion:
    enabled: false
    parameters:
      rsi_period: 5
      overbought: 65
      oversold: 35
      mean_period: 10
  
  volatility_breakout:
    enabled: false
    parameters:
      bollinger_period: 20
      bollinger_std: 2
      volume_threshold: 1.5

risk_management:
  position_sizing:
    max_position_size: 50
    risk_per_trade: 0.02
  
  stop_loss:
    enabled: true
    percentage: 0.005
    trailing: true
  
  take_profit:
    enabled: true
    percentage: 0.01
    trailing: false
  
  portfolio:
    max_drawdown: 0.05
    max_open_positions: 1
    correlation_threshold: 0.7

logging:
  level: DEBUG
  save_trades: true
  telegram_notifications: false 