exchange:
  name: binance
  trading_type: future
  test_mode: false

trading:
  base_currency: USDT
  quote_currencies:
    - BTC
    - ETH
    - XRP
    - ADA
    - LINK
    - HBAR
    - AVAX
    - DOT
    - NEAR
    - ICP
    - ONDO
    - RENDER
    - S
    - FET
    - SEI
    - STX
    - IOTA
    - KDA
    - FLUX
  timeframe: 1m
  leverage: 10
  loop_interval: 15
  order_types:
    - market
    - limit
    - stop_loss
    - take_profit

strategies:
  trend_following:
    enabled: true
    parameters:
      # Use very small SMA periods to ensure we have enough data
      sma_short: 3      # Only 3 minutes of data needed
      sma_long: 5       # Only 5 minutes of data needed
      trend_threshold: 0.0005  # Much smaller threshold to catch more trades
      allow_default_trades: true   # Allow default trades if needed
      force_trades: false  # Don't force trades yet
      debug_mode: false    # Not in debug mode
      stop_loss_pct: 0.005 # 0.5% stop loss
      take_profit_pct: 0.01 # 1% take profit
  
  mean_reversion:
    enabled: false
    parameters:
      rsi_period: 5
      overbought: 65
      oversold: 35
      mean_period: 10
  
  volatility_breakout:
    enabled: false
    parameters:
      bollinger_period: 20
      bollinger_std: 2
      volume_threshold: 1.5

risk_management:
  position_sizing:
    max_position_size: 50  # Maximum 50 contracts
    risk_per_trade: 0.02   # 2% risk per trade
  
  stop_loss:
    enabled: true
    percentage: 0.005  # 0.5% stop loss
    trailing: true
  
  take_profit:
    enabled: true
    percentage: 0.01  # 1% take profit
    trailing: false
  
  portfolio:
    max_drawdown: 0.05     # 5% maximum drawdown
    max_open_positions: 3  # Allow up to 3 positions at a time
    correlation_threshold: 0.7

logging:
  level: DEBUG
  save_trades: true
  telegram_notifications: false 